In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

emb=pd.read_csv('string_v12.csv')
emb["Unnamed: 0"]=emb["Unnamed: 0"].str.split('.').str[1]
prot_ids=pd.read_csv('prot_converter.csv')

print(f"emb {len(emb)}")
display(emb.head())

print(f"prot_ids {len(prot_ids)}")
display(prot_ids.head())

emb 19622

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,90,91,92,93,94,95,96,97,98,99
0,ENSP00000000233,0.004280,0.019731,-0.072885,0.032266,-0.018992,0.128898,0.035430,-0.203360,-0.011699,...,0.015443,0.099613,-0.135344,0.136229,0.000996,0.014312,0.212254,0.055522,-0.166588,-0.113687
1,ENSP00000356607,0.081169,-0.032808,0.054809,0.065385,0.067155,0.075120,-0.079834,-0.140763,-0.117879,...,0.035314,0.016878,-0.184513,0.019691,-0.058561,-0.040620,0.176866,-0.003070,-0.032281,-0.044648
2,ENSP00000427567,-0.063502,-0.033807,-0.012120,0.026970,0.056772,0.075502,-0.058227,-0.034033,-0.051017,...,-0.007382,0.000500,-0.150628,0.114056,0.039647,-0.160611,0.190874,0.062045,-0.028040,-0.157163
3,ENSP00000325266,0.006151,-0.118425,-0.140054,0.059499,-0.012661,-0.006386,0.103093,-0.029687,0.069771,...,-0.041509,-0.067730,0.130109,0.047968,0.136339,0.222452,0.184334,0.178143,-0.252154,-0.013617
4,ENSP00000324127,-0.093723,-0.091282,0.099704,0.080748,0.065582,0.061732,-0.046076,-0.116664,-0.101095,...,-0.045360,0.017148,-0.137438,0.044422,-0.165427,-0.061849,0.051732,-0.038064,0.099564,-0.042957

prot_ids 23773

       syb     ensb_gene_id     ensb_prot_id
0   MT-ND2  ENSG00000198763  ENSP00000355046
1   MT-CO1  ENSG00000198804  ENSP00000354499
2   MT-CO2  ENSG00000198712  ENSP00000354876
3  MT-ATP8  ENSG00000228253  ENSP00000355265
4  MT-ATP6  ENSG00000198899  ENSP00000354632

## Merge the two

In [18]:
embedding_file = pd.merge(prot_ids, emb, left_on='ensb_prot_id', right_on='Unnamed: 0', how='inner')
embedding_file

,syb,ensb_gene_id,ensb_prot_id,Unnamed: 0,0,1,2,3,4,5,...,90,91,92,93,94,95,96,97,98,99
0,MT-ND2,ENSG00000198763,ENSP00000355046,ENSP00000355046,0.075598,0.059693,-0.183821,-0.011878,-0.064288,0.100463,...,-0.072614,0.122145,-0.082446,-0.002946,0.103807,0.145590,0.001029,0.054062,-0.104490,0.085482
1,MT-CO1,ENSG00000198804,ENSP00000354499,ENSP00000354499,0.069682,0.111846,-0.164253,-0.033847,-0.072215,0.050593,...,-0.044474,0.141194,-0.035790,0.032916,0.084927,0.136080,-0.023590,-0.014888,-0.135688,0.070739
2,MT-CO2,ENSG00000198712,ENSP00000354876,ENSP00000354876,0.085303,0.099716,-0.170778,-0.015281,-0.085338,0.052451,...,-0.043404,0.144494,-0.014183,0.034006,0.078419,0.170962,-0.016083,-0.013638,-0.164281,0.077133
3,MT-ATP8,ENSG00000228253,ENSP00000355265,ENSP00000355265,0.040221,0.073506,-0.178463,-0.012690,-0.173599,0.042014,...,-0.037674,0.144820,0.019771,0.042906,0.059785,0.209505,-0.080690,0.005613,-0.100568,0.084407
4,MT-ATP6,ENSG00000198899,ENSP00000354632,ENSP00000354632,0.041603,0.058167,-0.185808,-0.000650,-0.107960,0.053629,...,-0.079174,0.118302,-0.005985,0.050470,0.077362,0.197104,-0.019086,0.017275,-0.144998,0.089213
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14769,SLC30A2,ENSG00000158014,ENSP00000363394,ENSP00000363394,0.046577,-0.000123,-0.012309,0.058182,0.070410,0.133408,...,-0.144220,0.048078,-0.075384,-0.033066,-0.037153,0.131191,0.002490,-0.021625,-0.066201,0.114112
14770,TRIM63,ENSG00000158022,ENSP00000363390,ENSP00000363390,-0.064747,0.053434,-0.077587,-0.020014,0.051710,-0.071831,...,0.118782,0.141058,-0.033951,-0.051670,0.032217,-0.113113,-0.062602,-0.017638,-0.083871,-0.256004
14771,FAM110D,ENSG00000197245,ENSP00000363386,ENSP00000363386,-0.105766,-0.059212,0.143882,-0.013808,0.115521,0.020991,...,-0.033083,-0.054219,-0.138849,-0.139170,-0.129898,-0.230483,-0.166348,-0.045219,0.310265,0.023258
14772,C1orf232,ENSG00000282872,ENSP00000489320,ENSP00000489320,-0.195428,-0.222175,0.070843,0.118182,0.064326,0.011558,...,-0.175019,-0.155053,0.010304,-0.015175,-0.034915,-0.049337,-0.030011,0.075795,0.130136,0.003375
14773,ZNF593,ENSG00000142684,ENSP00000363384,ENSP00000363384,-0.070319,-0.023871,-0.156140,-0.041557,-0.214891,-0.038781,...,-0.019235,0.037875,0.054143,0.094140,0.056938,0.151065,-0.084791,0.068534,-0.011310,0.038506

In [23]:
embedding_file.to_csv('string_embedding.csv')

## test the new embeddings

In [49]:
import pandas as pd
gene_list=pd.read_csv('gene_lists/gene_list_krs_clean.csv')
gene_list

                 gene  y
0     ENSG00000138650  1
1     ENSG00000147133  1
2     ENSG00000165476  1
3     ENSG00000186153  1
4     ENSG00000075043  1
...               ... ..
1949  ENSG00000036473  0
1950  ENSG00000121207  0
1951  ENSG00000134755  0
1952  ENSG00000158169  0
1953  ENSG00000125845  0

[1954 rows x 2 columns]

In [50]:
positive_genes=gene_list[gene_list['y']==1]
negative_genes=gene_list[gene_list['y']==0]

In [51]:
print(f"positive genes {len(positive_genes)}")
print(f"negative genes {len(negative_genes)}")

positive genes 1161
negative genes 793

In [52]:
positive_genes_l=set(positive_genes["gene"].to_list())
negative_genes_l=set(negative_genes["gene"].to_list())
emb_gene_set=set(embedding_file["ensb_gene_id"].to_list())

In [58]:
print(f'number of positive genes in the emb file: {len(positive_genes_l & emb_gene_set)}')
print(f"number of negative genes in the emb file: {len(negative_genes_l & emb_gene_set)}")
print(f"number of negative + positives in the emb file: {len((positive_genes_l|negative_genes_l))}")
print(f"total number of genes from the gene list in the emb file: {len((positive_genes_l|negative_genes_l) & emb_gene_set)}")
print(f"total number of genes in the emb file: {len(emb_gene_set)}")

number of positive genes in the emb file: 825
number of negative genes in the emb file: 605
number of negative + positives in the emb file: 1954
total number of genes from the gene list in the emb file: 1430
total number of genes in the emb file: 14774

# cat1_sd

In [54]:
cat1_sd=pd.read_csv('gene_lists/cat_1_sd.csv.gz',compression='gzip')
cat1_sd_genes=set(cat1_sd["ensb_gene_id"].to_list())

In [55]:
len(cat1_sd_genes & emb_gene_set)

828

In [56]:
print(f"positive genes: {cat1_sd[cat1_sd['y']==1].shape}")
print(f"negative genes: {cat1_sd[cat1_sd['y']==0].shape}")

positive genes: (223, 104)
negative genes: (605, 104)