In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

emb=pd.read_csv('gene_lists/Node2Vec.csv')
#emb["Unnamed: 0"]=emb["Unnamed: 0"].str.split('.').str[1]
prot_ids=pd.read_csv('prot_converter.csv')
prot_ids=prot_ids.rename(columns={"ensb_gene_id":"Ensb_gene_id","ensb_prot_id":"Ensb_prot_id"})

print(f"emb {len(emb)}")
display(emb.head())

print(f"prot_ids {len(prot_ids)}")
display(prot_ids.head())

emb 19170

,Unnamed: 0.1,Unnamed: 0,0,1,2,3,4,5,6,7,...,93,94,95,96,97,98,99,syb,ensb_gene_id,ensb_prot_id
0,0,ENSG00000232810,0.337997,-0.682200,0.651600,0.392280,1.679922,1.516125,0.382458,-0.906855,...,-0.700907,0.176625,0.212016,-0.798409,-0.330800,0.431094,0.135376,TNF,ENSG00000232810,ENSP00000398698
1,1,ENSG00000067182,0.444571,-1.524992,0.405095,0.173764,1.289201,1.644505,0.669241,-0.928645,...,-0.813190,0.558204,0.659598,0.504645,-0.228550,0.736030,-0.149118,TNFRSF1A,ENSG00000067182,ENSP00000162749
2,2,ENSG00000164338,-0.367288,0.398485,-0.125841,-0.697462,-0.339018,-1.791960,0.325434,0.208727,...,-0.671808,-0.645977,-1.483410,-0.005678,1.053632,-0.820771,0.384354,UTP15,ENSG00000164338,ENSP00000296792
3,3,ENSG00000108651,1.403058,-1.346653,0.518801,-0.166207,-1.697061,-2.316402,0.526102,0.223622,...,-0.196413,-1.530074,-0.528354,0.431240,-0.347294,0.102289,0.370970,UTP6,ENSG00000108651,ENSP00000261708
4,4,ENSG00000198899,0.183781,0.022639,-0.655331,-0.536686,-0.671601,-1.324415,-0.633466,-0.119998,...,1.140562,-1.106292,-0.862765,-0.429610,-0.082736,-0.012132,-0.288675,MT-ATP6,ENSG00000198899,ENSP00000354632

prot_ids 23773

       syb     Ensb_gene_id     Ensb_prot_id
0   MT-ND2  ENSG00000198763  ENSP00000355046
1   MT-CO1  ENSG00000198804  ENSP00000354499
2   MT-CO2  ENSG00000198712  ENSP00000354876
3  MT-ATP8  ENSG00000228253  ENSP00000355265
4  MT-ATP6  ENSG00000198899  ENSP00000354632

## Merge the two

In [7]:
embedding_file = pd.merge(prot_ids, emb, left_on='Ensb_gene_id', right_on='Unnamed: 0', how='inner')
embedding_file

,syb_x,Ensb_gene_id,Ensb_prot_id,Unnamed: 0.1,Unnamed: 0,0,1,2,3,4,...,93,94,95,96,97,98,99,syb_y,ensb_gene_id,ensb_prot_id
0,MT-ND2,ENSG00000198763,ENSP00000355046,266,ENSG00000198763,-1.181143,-1.366331,-1.279245,0.823244,0.412206,...,-0.409058,-0.830555,-1.601284,-0.290230,-2.413858,0.597801,-1.192459,MT-ND2,ENSG00000198763,ENSP00000355046
1,MT-CO1,ENSG00000198804,ENSP00000354499,3048,ENSG00000198804,-1.046846,-0.468488,-0.226454,0.829274,-1.329101,...,-0.303123,-1.306434,-1.034553,-1.390777,-0.310004,-0.095381,0.815198,MT-CO1,ENSG00000198804,ENSP00000354499
2,MT-CO2,ENSG00000198712,ENSP00000354876,386,ENSG00000198712,-0.573655,-0.923794,-0.199594,-0.190053,-0.609827,...,-1.498140,-0.810674,-1.658923,-0.125378,-0.147086,0.075579,-0.583272,MT-CO2,ENSG00000198712,ENSP00000354876
3,MT-ATP8,ENSG00000228253,ENSP00000355265,495,ENSG00000228253,-0.689088,0.136256,-0.000191,-1.268772,-1.080368,...,1.231444,-0.215480,-1.412499,-0.575033,-0.532775,0.409826,0.071224,MT-ATP8,ENSG00000228253,ENSP00000355265
4,MT-ATP6,ENSG00000198899,ENSP00000354632,4,ENSG00000198899,0.183781,0.022639,-0.655331,-0.536686,-0.671601,...,1.140562,-1.106292,-0.862765,-0.429610,-0.082736,-0.012132,-0.288675,MT-ATP6,ENSG00000198899,ENSP00000354632
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19165,PDIK1L,ENSG00000175087,ENSP00000363387,12698,ENSG00000175087,-0.110959,-0.930807,-1.895706,-0.802330,-1.378628,...,-0.953243,-0.435804,-1.053045,0.846091,-0.764025,-0.846429,0.176935,PDIK1L,ENSG00000175087,ENSP00000363387
19166,FAM110D,ENSG00000197245,ENSP00000363386,17928,ENSG00000197245,-0.471025,-0.393942,-1.161112,-0.384733,-1.510082,...,-0.573202,0.254157,-0.439561,0.495672,-0.174687,0.520281,0.119904,FAM110D,ENSG00000197245,ENSP00000363386
19167,C1orf232,ENSG00000282872,ENSP00000489320,13612,ENSG00000282872,-0.873396,1.382934,-1.373172,-0.496917,-0.301437,...,0.536174,0.166477,0.409374,0.612030,-0.472452,-0.247611,-0.167932,C1orf232,ENSG00000282872,ENSP00000489320
19168,ZNF593,ENSG00000142684,ENSP00000363384,5049,ENSG00000142684,-1.249594,-0.576874,-0.151592,-0.895912,0.814364,...,-1.128149,-0.874445,-0.612937,-0.792863,-0.524122,0.185118,-0.269448,ZNF593,ENSG00000142684,ENSP00000363384
19169,CNKSR1,ENSG00000142675,ENSP00000354609,10606,ENSG00000142675,-0.821163,0.952440,0.229183,1.032671,0.006333,...,0.072591,0.697905,1.729385,-1.094912,0.390858,-1.667568,0.056495,CNKSR1,ENSG00000142675,ENSP00000354609

In [8]:
embedding_file.to_csv('string_embedding.csv')

## test the new embeddings

In [9]:
import pandas as pd
gene_list=pd.read_csv('gene_lists/gene_list_krs_clean.csv')
gene_list

                 gene  y
0     ENSG00000138650  1
1     ENSG00000147133  1
2     ENSG00000165476  1
3     ENSG00000186153  1
4     ENSG00000075043  1
...               ... ..
1949  ENSG00000036473  0
1950  ENSG00000121207  0
1951  ENSG00000134755  0
1952  ENSG00000158169  0
1953  ENSG00000125845  0

[1954 rows x 2 columns]

In [10]:
positive_genes=gene_list[gene_list['y']==1]
negative_genes=gene_list[gene_list['y']==0]

In [11]:
print(f"positive genes {len(positive_genes)}")
print(f"negative genes {len(negative_genes)}")
print(f"total genes {len(gene_list)}")

positive genes 1161
negative genes 793
total genes 1954

In [12]:
positive_genes_l=set(positive_genes["gene"].to_list())
negative_genes_l=set(negative_genes["gene"].to_list())
emb_gene_set=set(embedding_file["ensb_gene_id"].to_list())

In [13]:
print(f'number of positive genes in the emb file: {len(positive_genes_l & emb_gene_set)}')
print(f"number of negative genes in the emb file: {len(negative_genes_l & emb_gene_set)}")
print(f"number of negative + positives in the emb file: {len(((positive_genes_l & emb_gene_set)|(negative_genes_l & emb_gene_set)))}")
print(f"total number of genes from the gene list in the emb file: {len((positive_genes_l|negative_genes_l) & emb_gene_set)}")
print(f"total number of genes in the emb file: {len(emb_gene_set)}")

number of positive genes in the emb file: 1136
number of negative genes in the emb file: 779
number of negative + positives in the emb file: 1915
total number of genes from the gene list in the emb file: 1915
total number of genes in the emb file: 19170

# cat1_sd

In [14]:
cat1_sd=pd.read_csv('gene_lists/cat_1_sd.csv.gz',compression='gzip')
cat1_sd_genes=set(cat1_sd["ensb_gene_id"].to_list())

In [15]:
len(cat1_sd_genes & emb_gene_set)

1101

In [16]:
print(f"positive genes: {cat1_sd[cat1_sd['y']==1].shape}")
print(f"negative genes: {cat1_sd[cat1_sd['y']==0].shape}")

positive genes: (322, 104)
negative genes: (779, 104)